CREATE TABLE TB_FUNCIONARIO
(ID INT NOT NULL AUTO_INCREMENT , 
NOME VARCHAR(50) NOT NULL ,
SALARIO DOUBLE NOT NULL ,
 PRIMARY KEY (ID));

#SELECT * FROM TB_FUNCIONARIO 

INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('FERNANDO', 200);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('GIOVANA', 300);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('THEO', 250);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('SOLANGE', 150);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('MARIA', 230);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('JOSE', 180);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('FULANO', 540);
INSERT INTO TB_FUNCIONARIO (NOME, SALARIO) VALUES ('SICLANO', 90);